### ISSUE TITLE
Determine claim cost to claimant

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#12]
*Description*
As a user, I want the system to tell me about legal costs regarding my claim

*Scope of Work*
- [ ] Research costs associated with each remedy found in #17 
- [ ] Create high fidelity UI mock-up
- [ ] Implement UI
- [ ] Implement back-end changes to add cost estimation.

*Acceptance Criteria*
- Upon completion of an interaction with our system, the user is shown a result dashboard.
- The cost associated with each remedy is displayed.

*Story Points*
- 20

*Priority*
- Low

*Risk*
- High

**Comment by arekmano** [comment]
Original Comment: "Legal fees (avg hourly rate * avg houras) + court fees (it's in a reglement); will NEED expertise from lawyers in droit du logement; use baseline and adjust according to some elements"

**Comment by arekmano** [comment]
Unless I am mistaken, this relies on completion of #10
