### ISSUE TITLE
Claim evidence gathering

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#15]
*Description*
- As a user, I want the system to prompt me for the evidence required to support my claim

*Scope of Work*
- [x] A low-fid designs for system
- [x] A mockup for evidence-gathering 
- [x] Improve UI based of product owner mockup choice
- [x] Implement backend server with db
- [x] Validate what pieces of evidence are required by law-domain expert (too vague, split into #80, #84 for now)
- [x] Determine all possible valid piece of evidence to be supplied by the user (too vague, split into #25 #26)
- [x] Obtain image/text file/decision from the user and store in database

*Acceptance Criteria*
- [x] Chatbot prompts user to provide relevant evidence for case (generic question)
- [x] Chatbot is able to prompt for all possible relevant evidence in a variety of scenarios [CANCELLED] (too vague, split into #80 , #84 )
- [x] User is able to provide evidence in textual and image-based formats
- [x] Chatbot is able to retrieve evidence in textual and image-based formats

*Story Points*
- 13

*Priority*
- High

*Risk*
- High

**Comment by arekmano** [comment]
- [ ] 3 UI designs for system (3h ideal time)
- [ ] 2 UI Mockups for evidence-gathering (2h ideal time)
- [ ] Improve UI based of product owner mockup choice (3h)
- [ ] Implement backend server with db (12h)
- [ ] Validate what pieces of evidence are required by law-domain expert (2h)
- [ ] Determine all possible valid piece of evidence to be supplied by the user (5h)
- [ ] Obtain image/text file/decision from the user and store in database (3h)
- [ ] Have a basic yes/no decision tree of what evidence to ask for (? h)

**Comment by arekmano** [comment]
As part of this user story, we should finalize the domain of law that we will be diving into

**Comment by arekmano** [comment]
UI Designs for both the system and the feature should be completed by this thursday, so that we can obtain feedback about it on friday.

**Comment by arekmano** [comment]
Acceptance criteria "Chatbot is able to prompt for all possible relevant evidence in a variety of scenarios" is overly broad. We have to limit this user story's scope.

**Comment by arekmano** [comment]
This story may also involve the creation and persistance of data in a database, that is capable of storing various types of data. Also "Have a basic yes/no decision tree of what evidence to ask for (? h)" is being worked on as a side-effect of #20. 

For "Validate what pieces of evidence are required by law-domain expert", we can limit this to images of a lease and receipts

**Comment by naregeff** [comment]
Does what it's supposed to do. Rest is in other user stories.
